### ISSUE TITLE
Player.gd is uppercase

### ISSUE THREAD

**Issue by OrionMelaeno** [gamesforklaus/brainfluff#4]
Sure, it would be easier to just make a fork, rename the file, and open a pull request with the commits, but I decided to leave this as an issue as this is more of a **case-sensitive bug with the script filename** rather than an actual change in the code.
Due to this bug, you're unable to ~place the puppet in the game world~ enter the game without it crashing back to the Godot editor.
Should be (VERY) easy to fix this.

**Comment by gamesforklaus** [comment]
Thats odd, I just renamed the file to what it's supposed to be. It's properly formatted on my local repo so im not sure how that slipped through. Try pulling again and seeing if that fixes things

**Comment by OrionMelaeno** [comment]
Yep, that fixed it, game no longer crashes on startup (even though I manually fixed it on my local folder).
Little things like that can break the game, thanks for fixing the issue (even though it was as simple as renaming it).

**Comment by gamesforklaus** [comment]
No problem, thank you for letting me know! :]
